version: '3.8'

services:
  analytics-app:
    build: .
    container_name: intelilegal_analytics_container
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # Mapeia seu código local para dentro do container em tempo real (Live Reload)
      - .:/app
    environment:
      - ENVIRONMENT=dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    # Mantém o terminal interativo aberto
    tty: true
    stdin_open: true